### ISSUE TITLE
[feature] Support gang scheduling configuration in common

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/common#113]
/cc @k82cn 

We now support gang scheduling by adding a CLI flag to enable it. We do not expose the ability to users, thus there are some complaints that we do not support queue, minresources and some other PodGroup fields.

I think we should support these:

```diff
type SchedulingPolicy struct {
	MinAvailable *int32 `json:"minAvailable,omitempty"`
+      Queue *string
+      MinResources *v1.ResourceList
+      PriorityClass *string
}
```

/assign

**Comment by k82cn** [comment]
That's great !

**Comment by shinytang6** [comment]
@gaocegege Is there any timeline for that? Can l take that?

**Comment by gaocegege** [comment]
@shinytang6 Sure, thanks for your contribution!

We do not have a clear plan for it.
