### ISSUE TITLE
Cut new release for kubeflow/common

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#119]
As @gaocegege suggested, we could cut a release as volcano support is fully integrated into kubeflow/common. 

https://github.com/kubeflow/common/compare/v0.3.2...master

Any other pending changes to include in this release?  Next release is v0.4.0? 

/cc @kubeflow/wg-training-leads

**Comment by terrytangyuan** [comment]
Perhaps 0.3.3 since there are only 4 commits since 0.3.2 unless there are significant changes I may have missed?

**Comment by gaocegege** [comment]
Is this release for 1.3?

Some features are not used now (e.g. https://github.com/kubeflow/common/commit/1c55acc7fa15c38ad47a80fb8c97d8d63f9a8748)

I think we can keep 0.3.2 in 1.3.

**Comment by shinytang6** [comment]
Maybe we should also replace the volcano dependency with volcano/apis in the next release.

ref: [https://github.com/volcano-sh/apis](https://github.com/volcano-sh/apis)

**Comment by gaocegege** [comment]
Yeah, I think so.

**Comment by Jeffwan** [comment]
> Is this release for 1.3?
> 
> Some features are not used now (e.g. [1c55acc](https://github.com/kubeflow/common/commit/1c55acc7fa15c38ad47a80fb8c97d8d63f9a8748))
> 
> I think we can keep 0.3.2 in 1.3.

Not necessary. I think release team already pin version in 1.3. kubeflow/common can have separate process

**Comment by gaocegege** [comment]
SGTM, then I think we can wait for volcano api changes, as @shinytang6 said.

**Comment by gaocegege** [comment]
Should we release a new version?

/cc @Jeffwan @shinytang6

**Comment by shinytang6** [comment]
> Should we release a new version?
> 
> /cc @Jeffwan @shinytang6

+1. Looking forward to that :)

**Comment by Jeffwan** [comment]
@gaocegege already cut the release. https://github.com/kubeflow/common/releases/tag/v0.3.3 👍 

We can close this issue.

**Comment by shinytang6** [comment]
@Jeffwan @gaocegege Is there any release plan for tf-operator/mpi-operator or other operator recently? l think we should plano to update the `common` version there.

**Comment by gaocegege** [comment]
We have the PR for tf-operator. After it is merged we can release a new version.

**Comment by Jeffwan** [comment]
> @Jeffwan @gaocegege Is there any release plan for tf-operator/mpi-operator or other operator recently? l think we should plan to update the `common` version there.

please help on rest of the repos.
