### ISSUE TITLE
Type of replicaType is not consistent in common project

### ISSUE THREAD

**Issue by MartinForReal** [kubeflow/common#134]
Is there any thought about why type of replicaType is not consistent across the common project?

e.g.

https://github.com/kubeflow/common/blob/eb55ddefdea6d4034af9f4fe66dd202ff3af400e/pkg/apis/common/v1/interface.go#L47

vs

https://github.com/kubeflow/common/blob/eb55ddefdea6d4034af9f4fe66dd202ff3af400e/pkg/apis/common/v1/interface.go#L57

I think maybe it is a good idea to define replicaType as commonv1.ReplicaType.

**Comment by Jeffwan** [comment]
It makes no difference from usage perspective but I agree we should make it consistent.
