### ISSUE TITLE
Proposal: Define a job type to track all kinds of jobs on the same cluster

### ISSUE THREAD

**Issue by MartinForReal** [kubeflow/common#145]
It would be better if we can apply a single set of rules to  all of jobs running on the cluster regardless of jobs' types.

Following information should be considered if we define an job type:

- roles and specs:
- policy
- Owner/Origin(e.g. tfjob, mpijob)
- status
optional:
- queue/quota 
- scheduling profile

We can see similar pattern in storage management, cluster management. e.g.
Machine and vendor-spesific machine type 
pvc and pv

**Comment by gaocegege** [comment]
Please have a look at https://docs.google.com/document/d/1x1JPDQfDMIbnoQRftDH1IzGU0qvHGSU4W6Jl4rJLPhI/edit

**Comment by Jeffwan** [comment]
@MartinForReal Feel free to check issues with "help wanted" tags and any contribution are welcomed.
