### ISSUE TITLE
Enable GitHub action to build and test code

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#162]
See https://github.com/kubeflow/common/pull/161

#141 introduces some build failures but we don't notice that before we merge the code. Travis somehow was deleted at that time. @gaocegege suggests to use Github actions. 

Let's migrate scripts https://github.com/kubeflow/common/blob/master/.travis.yml to a Github Action manner.

We do need this to guarantee code quality 

/help
/good-first-issue

**Comment by Jeffwan** [comment]
https://github.com/kubeflow/common/runs/3648012266 Interesting, in the latest workflow, I didn't see failure logs..

**Comment by SumLare** [comment]
Well https://status.coveralls.io/ still doesn't look good

**Comment by Jeffwan** [comment]
Yeah, that's the problem

```
bad response status from coveralls: 503
<h2>This website is under heavy load (queue full)</h2><p>We're sorry, too many people are accessing this website at the same time. We're working on this problem. Please try again later.</p>

```

**Comment by gaocegege** [comment]
coveralls crashes sometimes.

**Comment by Jeffwan** [comment]
Let's do this to overcome the issue. Since goveralls is nice to have, we can ignore the failures in CI. I can not believe recovery takes that long.. 

`goveralls || echo "push to coveralls failed"`

**Comment by Jeffwan** [comment]
This can be closed. thanks @SumLare !
