### ISSUE TITLE
Limit the number of restarts under ExitCode restartPolicy

### ISSUE THREAD

**Issue by goyalankit** [kubeflow/common#167]
In the current [implementation](https://github.com/kubeflow/common/blob/master/pkg/core/job.go#L86-L89), the `runPolicy.BackoffLimit` is only applicable on `OnFailure` and `Always` restart policies. I was wondering if there's a reason it's not supported on the `ExitCode` restart policy. Often in the case of OOM, the job exits with an exit code of 137 which is rightfully a retriable error. However, it will keep restarting indefinitely since the policy is not covered by the `BackOffLimit`. The behavior could be to honor the backOffLimit if present, else it keeps retrying indefinitely?

I am happy to submit a PR if you think this is a reasonable change.

**Comment by gaocegege** [comment]
Hi @goyalankit . Thanks for the issue.

I think it makes sense, WDYT @kubeflow/wg-training-leads

**Comment by Jeffwan** [comment]
I think this is reasonable improvement. @goyalankit Feel free to cut a PR and assign to us to help review

**Comment by johnugeorge** [comment]
Thanks for this
