### ISSUE TITLE
Does package name github.com/stretchr/testify/assert correct ? 

### ISSUE THREAD

**Issue by merlintang** [kubeflow/common#23]
For the test job of common, 
the assert function i.e., https://github.com/stretchr/testify/assert is already moved to 
https://github.com/stretchr/testify/tree/master/assert. Should we also change the related https://github.com/kubeflow/common/blob/master/job_controller/job_test.go#L9 as well ?

**Comment by gaocegege** [comment]
Sorry, I am a little confused. Do you mean the package is moved?

**Comment by merlintang** [comment]
> Sorry, I am a little confused. Do you mean the package is moved?

yes, the package name is changed. thus import old name would bring error.

**Comment by gaocegege** [comment]
We have vendored the dep, thus it may not affect us now. BTW, what's the name of the package is now? https://github.com/stretchr/testify/tree/master/assert 's package name is github.com/stretchr/testify/assert, which is same as the name in the current code.

**Comment by merlintang** [comment]
@gaocegege I do not see the dep in the common directory, do we have prepared the vendor dep ?

**Comment by terrytangyuan** [comment]
@merlintang No we are not keeping vendor in the repo yet (currently it’s gitignored). I just opened https://github.com/kubeflow/common/pull/28 so let's discuss this separate issue there.

**Comment by merlintang** [comment]
@terrytangyuan  Thanks for following up this.
