### ISSUE TITLE
Re organize the API package

### ISSUE THREAD

**Issue by jian-he** [kubeflow/common#38]
Right now the user facing APIs are scattered in different packages, we should re-organize them into a central api package. 
A proposal looks like below:

![image](https://user-images.githubusercontent.com/3662775/58211618-4d4d4800-7ca1-11e9-9c68-e6be92ba1f12.png)

1.  types.go
2. [new file] interface.go:  the ControllerInterface for custom operators to override
3. [new file] controller.go: the JobController struct which contains the ReconcileJobs entry method.
4. [new file] constants.go: the constant such as the label keys: job-name, replica-index, etc.

**Comment by jian-he** [comment]
@richardsliu @johnugeorge @terrytangyuan  opinions ?

**Comment by richardsliu** [comment]
Makes sense to me.

**Comment by terrytangyuan** [comment]
+1
