### ISSUE TITLE
Make training container port optional

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#56]
Instead of using fixed port to communicate with each other, some frameworks randomly pick up port by worker and use auto-discovery to find entire topology in consensus store. 

Currently, common force user to implement `GetDefaultContainerPortName` and `GetDefaultContainerPortNumber` and use it in following logic.  

https://github.com/kubeflow/common/blob/64f943084a050ac84b50ce4f49b6b6e085b247e6/pkg/controller.v1/common/service.go#L174

If job doesn't have port, it will return an error. 

In order to make this change, we can make this optional to meet the case I described above.

**Comment by terrytangyuan** [comment]
Sounds good to me.

**Comment by Jeffwan** [comment]
PR has been merged and I will close the issue
