### ISSUE TITLE
Allow user to submit jobs using Git repo without building container images

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/common#66]
This is part of the [roadmap](https://github.com/kubeflow/common/blob/master/ROADMAP.md).

**Comment by merlintang** [comment]
good point, and would like to watch how to solve it.

**Comment by ca-scribner** [comment]
Has there been any work on this, or any more detailed docs on what this should be/how to achieve it?  It sounds of interest, but I'm not sure whether it is meant to be:
* user does `kfp.run_from_repo(path_to_repo, base_image)` and kfp git clones/runs the python code from the repo in the base image, sort of like a lightweight component
* user does `kfp.run_from_repo(path_to_repo, base_image)` and kfp **builds** containers based on the repo and runs the code
* something else?

**Comment by omerfsen** [comment]
+1
