### ISSUE TITLE
Failed to fetch common module

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#70]
Following command doesn't work. 

```
$ go get github.com/kubeflow/common
go: finding github.com/kubeflow/common latest
go get: github.com/kubeflow/common@v0.0.0-20200413165349-fda69c7bdd38 requires
	k8s.io/kubernetes@v1.18.0 requires
	k8s.io/kubectl@v0.0.0: reading k8s.io/kubectl/go.mod at revision v0.0.0: unknown revision v0.0.0
```

I think this is because of #62. 

I use the stable version here for now and I will fix this when I get time.

```
$ go get github.com/kubeflow/common@v0.0.0-20200327002023-0b3a4c3fca85
go: finding github.com/kubeflow/common v0.0.0-20200327002023-0b3a4c3fca85
go: downloading github.com/kubeflow/common v0.0.0-20200327002023-0b3a4c3fca85
go: extracting github.com/kubeflow/common v0.0.0-20200327002023-0b3a4c3fca85
```

**Comment by k82cn** [comment]
@hzxuzhonghu , please also help to check this :)

**Comment by hzxuzhonghu** [comment]
@Jeffwan It is not the pr i filed introduced this issue.
```
go get github.com/kubeflow/common@461336009d7f8e9c97db6de123265accce7e7e36
go: finding github.com 461336009d7f8e9c97db6de123265accce7e7e36
go: finding github.com/kubeflow/common 461336009d7f8e9c97db6de123265accce7e7e36
go: finding github.com/kubeflow 461336009d7f8e9c97db6de123265accce7e7e36
go: downloading github.com/kubeflow/common v0.0.0-20200413165149-461336009d7f
go: extracting github.com/kubeflow/common v0.0.0-20200413165149-461336009d7f
go get: github.com/kubeflow/common@v0.0.0-20200413165149-461336009d7f requires
	k8s.io/kubernetes@v1.15.10 requires
	k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by hzxuzhonghu** [comment]
with ` go get github.com/kubeflow/common@v0.0.0-20200327002023-0b3a4c3fca85` i still get the same error

**Comment by hzxuzhonghu** [comment]
Not sure why, it is weird how i can import latest from tf-operator.

https://github.com/kubeflow/tf-operator/pull/1152

**Comment by Jeffwan** [comment]
@hzxuzhonghu I am not 100% sure this is related to the PR. Technically, once we replace libraries, it should be fine. Let me double check my environment. 

I can confirm that if I import this separately, both latest and previous one won't work.
If I update it inside a project, latest doesn't work for me and previous commit works.

**Comment by Jeffwan** [comment]
@hzxuzhonghu @k82cn  I think I figure it out. Sorry about the confusion. If one project doesn't have all component replaced, it may have this issue. In order to use `kubeflow/common`, we need to make sure it replace all kubernetes components. In my case, `mxnet-operaror` miss one `kubectl`. that's the failure come from. Thanks for the help.

**Comment by hzxuzhonghu** [comment]
For those meeting the similar issue: https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505627280

**Comment by Jeffwan** [comment]
@hzxuzhonghu The problem is `kubectl` is not part of distribution in kubernetes 1.15. #62 brings latest 1.18 change which has `kubectl` has part of the kubernetes. Operators without `kubectl` replace will failed to fetch the dependency. That's the root cause. If you see https://github.com/kubernetes/kubernetes/issues/79384#issuecomment-505627280, it doesn't have `kubectl` as well. version by version is a little bit different.

**Comment by Jeffwan** [comment]
This is interesting. I notice `mxnet-operator` doesn't have `kubectl` replace can `go get github.com/kubeflow/common@v0.0.0-20200327002023-0b3a4c3fca85` successfully. 

I think the problem is more on the Kubernetes side. most of the components including `kfctl` has been moved to `staging` which means kubernetes use `v0.0.0` for reference. This means we don't need `kfctl` override in the project untill we graduate to kubernetes 1.16 and above. 

Since we upgrade to 1.18 in PR #62, this requires a change on the operator which uses this lib to have a separate record to override `kfctl`.
