### ISSUE TITLE
Difference between kubeflow/common and kubeflow/tf-operator/pkg/common

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#71]
Comparing `ControllerInterface` between two different projects, tf-operator is pretty clean. `kubeflow/common` adds extra methods to create Job/Pod/Services. 

https://github.com/kubeflow/common/blob/fda69c7bdd3870ab5981538542c2e6b01fe076be/pkg/apis/common/v1/interface.go#L31-L56

Besides that, we extracted a few interfaces for high level abstraction which makes sense. https://github.com/kubeflow/common/blob/fda69c7bdd3870ab5981538542c2e6b01fe076be/pkg/apis/common/v1/interface.go#L59-L72

JobController side, tf-operator has `PodControl` and `ServiceControl` which are used to operate k8s objects. However, in https://github.com/kubeflow/common/pull/36, since create/delete pods/services interface have been exposed, community determine to remove `PodControl` and `ServiceControl` because them are kubernetes controller internal codes, and there's also concern on the size of the dependency (need kubernetes code base). 

Currently, it's a little bit weird. 

1. We can not fully get rid of `kubernetes/pkg/controller`, Expectation is still using them here. https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/job_controller.go#L100 . This is not part of `client-go` yet. See issue https://github.com/kubernetes/client-go/issues/332

I think we used `dep` to manage dependencies in the past and I've migrated common to go module compatible. Ideally, we will move all operator to go modules pretty soon. Size of the dependencies is not that painful. 

2. Files https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/pod_control.go and https://github.com/kubeflow/common/blob/master/pkg/controller.v1/common/service_control.go are not being used in `kubeflow/common`. 

I think we only one of following three. The status in `kubeflow/common` is 

- Create Pods/Service Interface  - exist and being used 
- controller. ServiceControlInterface - deleted
- copied ServiceControlInterface - still there and but not being used. Only tests are using it.

3. Implementation from different operators for following interface are very close. I doubt we need different controller to have similar logic there. Currently, only xgboost-operator is built on top of this operator, we have plan to migrate tf, pytorch, mxnet to follow kubeflow/common fashion.  trying to see any other operators are built on top of common, if there's a need to customize logic of `CreateService`, etc. If that's all same, it's better to implement it inside JobController. 

https://github.com/kubeflow/common/blob/fda69c7bdd3870ab5981538542c2e6b01fe076be/pkg/apis/common/v1/interface.go#L31-L38
https://github.com/kubeflow/common/blob/fda69c7bdd3870ab5981538542c2e6b01fe076be/pkg/apis/common/v1/interface.go#L47-L56

**Comment by gaocegege** [comment]
Thanks for the issue. It is helpful. Will we have plan to migrate tf-operator to common?

**Comment by terrytangyuan** [comment]
@Jeffwan Thanks for tracking down the differences! 

@gaocegege Yes, check out the [current roadmap](https://github.com/kubeflow/common/blob/master/ROADMAP.md) and we are tracking it in https://github.com/kubeflow/common/issues/64.

**Comment by Jeffwan** [comment]
I think my plan is to leave the interface for now.. I will have default implementation for following methods in `JobController` which is the our base controller in common. I will consider to use `https://github.com/kubeflow/tf-operator/tree/master/pkg/control` or kubernetes implementation directly (Consider the truth we can not move off Kubernetes due to expectation dependency). 

Then other controllers can reuse the implementation of JobController and they can still override following methods if they need a different implementation.

- CreatePod
- DeletePod
- GetPodsForJob
- CreateService
- DeleteService
- GetPodsForService

**Comment by Jeffwan** [comment]
Some conclusion

1. We create a package in common for PodControl and ServiceControl. Pod/Services CRUD should use `control` package instead of exposing to end users
2. Still expose `GetPodsForService` and `GetServicesForJob` as interfaces and  `common` provides common implementation. User can override implementation based on the needs.  I learnt this in XGBoost operator migration, the problem is projects built by Kubebuilder (like XGBoost Operator) doesn't use low level `informer` or `lister`. In order to leverage common implementation, user has to pass in `PodLister` and `ServiceLister` which is not elegant in kubebuilder implementation. 
3.
