### ISSUE TITLE
[Release 1.1] training operator release 

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/common#97]
Opening this issue to track releasing training operators for Kubeflow 1.1 and would like to add area OWNERS for @johnugeorge  @terrytangyuan @Jeffwan 

Seems we want to these works done before 1.1 release. We may not finish all of them but let's have a try. 

- Migration operator implementation to  kubeflow/common fashion. (TF, PyTorch in pending)
  - https://github.com/kubeflow/tf-operator/pull/1171  @ChanYiLin 
  - https://github.com/kubeflow/pytorch-operator/issues/282
- Graduate Operator to v1
  - MXNet Operator https://github.com/kubeflow/mxnet-operator/issues/66
  - XGBoost Operator https://github.com/kubeflow/xgboost-operator/issues/44
  - MPI Operator https://github.com/kubeflow/mpi-operator/issues/217

**Comment by terrytangyuan** [comment]
@Jeffwan Shouldn't we go through some sort of review process before the graduation of operators though? I don't think we would have sufficient time to finish that before 1.1 release.

**Comment by jlewi** [comment]
* the apps cd pipelines have been fixed
* application owners please review PRs to update your apps and ensure they get merged
    * https://github.com/kubeflow/manifests/pulls/kubeflow-bot

/cc @terrytangyuan @Jeffwan

**Comment by Jeffwan** [comment]
@terrytangyuan 

Agree. I think once these operator meet done criterion, then they can be graduated. It would be better for us to connect owners and have some discussion. If we can not catch 1.1, I think it's fine.

**Comment by jlewi** [comment]
@terrytangyuan @Jeffwan any update?

**Comment by terrytangyuan** [comment]
I think we should be ready regarding manifests (@Jeffwan correct me if I am wrong). Although There seems to be more [pending auto PRs](https://github.com/kubeflow/manifests/pulls/kubeflow-bot). @Jeffwan Could you check whether they need to be merged to master and cherry-picked to 1.1 release branch?

**Comment by Jeffwan** [comment]
1.1 and 1.2 release are done. We may not use exact same version as Kubeflow in the future. WG operators will have their own branch or tags. We just need to make sure we bring the right version to kubeflow release.
